export const stateOptions = [
    { value: 'AC', label: 'Acre' },
    { value: 'AL', label: 'Alagoas' },
    { value: 'AM', label: 'Amazonas' },
    { value: 'AP', label: 'Amapá' },
    { value: 'BA', label: 'Bahia' },
    { value: 'CE', label: 'Ceará' },
    { value: 'DF', label: 'Distrito Federal' },
    { value: 'ES', label: 'Espírito Santo' },
    { value: 'GO', label: 'Goiás' },
    { value: 'MA', label: 'Maranhão' },
    { value: 'MG', label: 'Minas Gerais' },
    { value: 'MS', label: 'Mato Grosso do Sul' },
    { value: 'MT', label: 'Mato Grosso' },
    { value: 'PA', label: 'Pará' },
    { value: 'PB', label: 'Paraíba' },
    { value: 'PE', label: 'Pernambuco' },
    { value: 'PI', label: 'Piauí' },
    { value: 'PR', label: 'Pará' },
    { value: 'RJ', label: 'Rio de Janeiro' },
    { value: 'RN', label: 'Rio Grande do Norte' },
    { value: 'RO', label: 'Rondônia' },
    { value: 'RR', label: 'Roraima' },
    { value: 'RS', label: 'Rio Grande do Sul' },
    { value: 'SC', label: 'Santa Catarina' },
    { value: 'SE', label: 'Sergipe' },
    { value: 'SP', label: 'São Paulo' },
    { value: 'TO', label: 'Tocantins' }
];

export const medicalOptions = [
    { value: '1', label: 'Alergia e Imunologia' },
    { value: '2', label: 'Anestesiologia' },
    { value: '3', label: 'Angiologia' },
    { value: '4', label: 'Cancerologia' },
    { value: '5', label: 'Cardiologia' },
    { value: '6', label: 'Cirurgia Cardiovascular' },
    { value: '7', label: 'Cirurgia da Mão' },
    { value: '8', label: 'Cirurgia de cabeça e pescoço' },
    { value: '9', label: 'Cirurgia do Aparelho Digestivo' },
    { value: '10', label: 'Cirurgia Geral' },
    { value: '11', label: 'Cirurgia Pediátrica' },
    { value: '12', label: 'Cirurgia Plástica' },
    { value: '13', label: 'Cirurgia Torácica' },
    { value: '14', label: 'Cirurgia Vascular' },
    { value: '15', label: 'Clínica Médica' },
    { value: '16', label: 'Coloproctologia' },
    { value: '17', label: 'Dermatologia' },
    { value: '18', label: 'Endocrinologia e Metabologia' },
    { value: '19', label: 'Endoscopia' },
    { value: '20', label: 'Gastroenterologia' },
    { value: '21', label: 'Genética médica' },
    { value: '22', label: 'Geriatria' },
    { value: '23', label: 'Ginecologia e obstetrícia' },
    { value: '24', label: 'Hematologia e Hemoterapia' },
    { value: '25', label: 'Homeopatia' },
    { value: '27', label: 'Infectologia' },
    { value: '27', label: 'Mastologia' },
    { value: '26', label: 'Medicina de Família e Comunidade' },
    { value: '28', label: 'Medicina de Emergência' },
    { value: '29', label: 'Medicina do Trabalho' },
    { value: '30', label: 'Medicina do Tráfego' },
    { value: '31', label: 'Medicina Esportiva' },
    { value: '32', label: 'Medicina Física e Reabilitação' },
    { value: '33', label: 'Medicina Intensiva' },
    { value: '34', label: 'Medicina Legal e Perícia Médica' },
    { value: '35', label: 'Medicina Nuclear' },
    { value: '36', label: 'Medicina Preventiva e Social' },
    { value: '37', label: 'Nefrologia' },
    { value: '38', label: 'Neurocirurgia' },
    { value: '39', label: 'Neurologia' },
    { value: '40', label: 'Nutrologia' },
    { value: '41', label: 'Obstetrícia' },
    { value: '42', label: 'Oftalmologia' },
    { value: '43', label: 'Ortopedia e Traumatologia' },
    { value: '44', label: 'Otorrinolaringologia' },
    { value: '45', label: 'Patologia' },
    { value: '46', label: 'Patologia Clínica/Medicina laboratorial' },
    { value: '47', label: 'Pediatria' },
    { value: '48', label: 'Pneumologia' },
    { value: '49', label: 'Psiquiatria' },
    { value: '50', label: 'Radiologia' },
    { value: '51', label: 'Radioterapia' },
    { value: '52', label: 'Reumatologia' },
    { value: '53', label: 'Urologia' }
];